### ISSUE TITLE
--regexp is obsolete

### ISSUE THREAD

**Issue by MarisElsins** [grugnog/google-cloud-auto-snapshot#2]
https://github.com/grugnog/google-cloud-auto-snapshot/blob/3bf5e98fed646c3140091dcde10869af6aec2d2b/google-cloud-auto-snapshot.sh#L17

replace `--regexp "(autogcs.*)"` with `--filter="name~'autogcs.*'"`

**Comment by MarisElsins** [comment]
actually, the correct syntax would be:
```
gcloud compute snapshots list --filter="creationTimestamp<$(date -d "-${DAYS_RETENTION} days" "+%Y-%m-%d") AND name~'autogcs.*'" --uri | while read SNAPSHOT_URI; do
```

**Comment by grugnog** [comment]
Thanks - I'll test this out when I get a chance

**Comment by ckaiwu** [comment]
Maris' solution worked for me.

**Comment by grugnog** [comment]
Committed - thanks!
